[package]
name = "mlibc-headers"
version = "latest"
archs = ["x86_64"]
shared_source = "mlibc"
host = true

[dependencies]
host = ["meson", "gcc", "as", "ld"]

[configure]
script = """
meson_configure -Dheaders_only=true
"""

[build]
script = """
ninja -j${THREADS}
"""

[install]
script = """
DESTDIR="${INSTALL_DIR}" ninja install
"""
