[package]
name = "gmp"
version = "6.3.0"
archs = ["x86_64"]

[dependencies]
build = ["host-binutils", "host-gcc", "host-autoconf", "host-automake"]

[[sources]]
url = "https://ftp.gnu.org/gnu/gmp/gmp-6.3.0.tar.xz"
path = "gmp-6.3.0.tar.xz"
patches = ["menix.patch"]

[configure]
script = """
autotools_configure --enable-cxx
"""

[build]
script = """
make -j${THREADS}
"""

[install]
script = """
make install
"""
