[package]
name = "limine"
version = "8.1.1"
archs = ["x86_64"]

[[sources]]
repo = "https://github.com/limine-bootloader/limine"
branch = "v8.1.1"

[dependencies]
host = ["make", "automake"]
build = ["host-binutils", "host-gcc"]

[configure]
script = """
if [ ${ARCH} = "x86_64" ]; then
	export ARCH=x86-64
fi

# Temporary workaround because -O0 seems to break
export CFLAGS=-O3
${SOURCE_DIR}/bootstrap

${SOURCE_DIR}/configure \
	TOOLCHAIN_FOR_TARGET=${OS_TRIPLET} \
    --enable-uefi-${ARCH} \
	--with-sysroot="${INSTALL_DIR}" \
	--prefix="${PREFIX}"
"""

[build]
script = """
make -j${THREADS}
"""

[install]
script = """
make install
mkdir -p ${INSTALL_DIR}/boot
cp ${PACKAGE_DIR}/limine.conf ${INSTALL_DIR}/boot/
mkdir -p ${INSTALL_DIR}/EFI/BOOT
cp -r ${INSTALL_DIR}/usr/share/limine/* ${INSTALL_DIR}/EFI/BOOT
"""
