[package]
name = "gcc"
version = "latest"
archs = ["x86_64"]
shared_source = "host-gcc"

[dependencies]
build = ["host-binutils", "host-gcc", "mlibc"]

[configure]
script = """
    CXXFLAGS_FOR_TARGET="${TARGET_CFLAGS}" \
    CFLAGS_FOR_TARGET="${TARGET_CFLAGS}" \
autotools_configure \
	--target=${OS_TRIPLET} \
	--enable-languages=c,c++,lto \
	--with-sysroot=/ \
	--with-build-sysroot="${SYSROOT_DIR}" \
	--prefix="${PREFIX}"
"""

[build]
script = """
make -j${THREADS} all-gcc all-target-libgcc all-target-libstdc++-v3
"""

[install]
script = """
DESTDIR="${INSTALL_DIR}" make install-gcc install-target-libgcc install-target-libstdc++-v3
"""
