[package]
name = "gcc"
version = "latest"
archs = ["x86_64"]
shared_source = "host-gcc"

[dependencies]
build = ["host-binutils", "host-gcc", "mlibc"]

[configure]
script = """
    CXXFLAGS_FOR_TARGET="${TARGET_CFLAGS}" \
    CFLAGS_FOR_TARGET="${TARGET_CFLAGS}" \
autotools_configure \
	--target=${OS_TRIPLET} \
	--enable-host-shared \
	--enable-languages=c,c++,lto \
	--with-sysroot=/ \
	--with-build-sysroot="${INSTALL_DIR}" \
	--prefix="${PREFIX}" \
	--disable-nls \
	--with-linker-hash-style=gnu \
	--enable-linker-build-id \
	--enable-default-pie \
	--enable-default-ssp \
	--disable-multilib \
	--enable-initfini-array
"""

[build]
script = """
make -j${THREADS} all-gcc
"""

[install]
script = """
DESTDIR="${INSTALL_DIR}" make install-gcc
"""
