[package]
name = "mlibc"
version = "latest"
archs = ["x86_64"]

[[sources]]
repo = "https://github.com/menix-os/mlibc"
branch = "add-menix"
path = "../../../mlibc"

[dependencies]
build = ["host-binutils", "host-gcc"]

[configure]
script = """
meson_configure
"""

[build]
script = """
ninja -j${THREADS}
"""

[install]
script = """
ninja install
"""
