[package]
name = "mlibc"
version = "latest"
archs = ["x86_64"]

[[sources]]
repo = "https://github.com/menix-os/mlibc"
branch = "master"
path = "../../../mlibc"

[dependencies]
build = ["host-tools"]

[configure]
script = """
"""

[build]
script = """
"""

[install]
script = """
"""
