[package]
name = "mlibc"
version = "latest"
archs = ["x86_64"]

[[sources]]
repo = "https://github.com/menix-os/mlibc"
branch = "add-menix"
path = "../../../mlibc"

[dependencies]
build = ["host-binutils", "host-gcc", "host-libgcc"]

[configure]
script = """
meson_configure -Ddefault_library=static -Dlibgcc_dependency=false
"""

[build]
script = """
ninja -j${THREADS}
"""

[install]
script = """
DESTDIR="${INSTALL_DIR}" ninja install
"""
