tasks:
- name: qemu
  tasks_required:
  - task: make-image
    order_only: true
  tools_required:
  - host-ovmf-bin
  args:
  - '@SOURCE_ROOT@/tasks/qemu.sh'
  - '@OPTION:arch@'
  - '@BUILD_ROOT@'
  - '@PARALLELISM@'
  - '@BUILD_ROOT@/tools/host-ovmf-bin/ovmf-code-@OPTION:arch@.fd'
  - '0'
  - '0'
  workdir: '@BUILD_ROOT@'
  containerless: true

- name: qemu-kvm
  tasks_required:
  - task: make-image
    order_only: true
  tools_required:
  - host-ovmf-bin
  args:
  - '@SOURCE_ROOT@/tasks/qemu.sh'
  - '@OPTION:arch@'
  - '@BUILD_ROOT@'
  - '@PARALLELISM@'
  - '@BUILD_ROOT@/tools/host-ovmf-bin/ovmf-code-@OPTION:arch@.fd'
  - '0'
  - '1'
  workdir: '@BUILD_ROOT@'
  containerless: true

- name: qemu-debug
  tasks_required:
  - task: make-image
    order_only: true
  tools_required:
  - host-ovmf-bin
  args:
  - '@SOURCE_ROOT@/tasks/qemu.sh'
  - '@OPTION:arch@'
  - '@BUILD_ROOT@'
  - '@PARALLELISM@'
  - '@BUILD_ROOT@/tools/host-ovmf-bin/ovmf-code-@OPTION:arch@.fd'
  - '1'
  - '0'
  workdir: '@BUILD_ROOT@'
  containerless: true
