[package]
name = "binutils"
version = "latest"
archs = ["x86_64"]
shared_source = "host-binutils"

[dependencies]
build = ["host-binutils", "host-gcc", "gmp", "mlibc"]

[configure]
script = """
    CXXFLAGS_FOR_TARGET="${TARGET_CFLAGS}" \
    CFLAGS_FOR_TARGET="${TARGET_CFLAGS}" \
autotools_configure \
	--target=${OS_TRIPLET} \
	--enable-cet \
	--enable-separate-code \
	--disable-nls \
	--disable-werror \
	--disable-dependency-tracking \
	--with-pic \
	--with-sysroot=/ \
	--with-build-sysroot="${SYSROOT_DIR}" \
	--prefix="${PREFIX}"
"""

[build]
script = """
make -j${THREADS}
"""

[install]
script = """
make install
"""
