[package]
name = "binutils"
version = "latest"
archs = ["x86_64"]

[[sources]]
repo = "https://sourceware.org/git/binutils-gdb.git"
branch = "master"
patches = ["menix.patch"]

[dependencies]
build = ["host-tools"]

[configure]
script = """
${SOURCE_DIR}/configure \
	--target=${OS_TRIPLET} \
	--enable-cet \
	--enable-separate-code \
	--disable-nls \
	--disable-werror \
	--disable-dependency-tracking \
	--with-pic \
	--with-sysroot="${INSTALL_DIR}"\
	--prefix="${PREFIX}"
"""

[build]
script = """
make -j${THREADS}
"""

[install]
script = """
DESTDIR="${INSTALL_DIR}" make install
"""
