[package]
name = "host-tools"
version = "latest"
archs = ["x86_64"]

[dependencies]
build = [
	"host-binutils",
	"host-gcc",
	"host-libgcc-binaries",
	# "host-cmake",
	# "host-automake",
	# "host-autoconf",
	# "host-pkg-config",
]
