[package]
name = "host-autoconf"
version = "2.69"
archs = ["x86_64"]
host = true

[[sources]]
url = "https://ftp.gnu.org/gnu/autoconf/autoconf-2.69.tar.xz"
path = "autoconf-2.69.tar.xz"

[dependencies]
host = ["autoconf"]
build = ["host-gcc"]

[configure]
script = """
${SOURCE_DIR}/configure --host="${OS_TRIPLET}" --prefix="${PREFIX_HOST}" --with-sysroot="${SYSROOT_DIR}"
"""

[build]
script = """
make -j${THREADS}
"""

[install]
script = """
DESTDIR="${INSTALL_DIR}" make install
"""
