[package]
name = "kernel"
version = "latest"
archs = ["x86_64"]

[dependencies]
build = ["base"]

[[sources]]
repo = "https://github.com/menix-os/menix"
branch = "rust_test"
path = "../../../menix"

[build]
script = """
if [ "${IS_DEBUG}" == "0" ]; then
	export BUILD_MODE="--release"
fi

cd ${SOURCE_DIR}
export RUSTUP_TOOLCHAIN=""
cargo build \
	${BUILD_MODE} \
	--lib \
	--target "${SOURCE_DIR}/toolchain/${ARCH}.json" \
	--target-dir "${BUILD_DIR}"
"""

[install]
script = """
if [ "${IS_DEBUG}" == "0" ]; then
	export CARGO_DIR="release"
else
	export CARGO_DIR="debug"
fi

mkdir -p ${INSTALL_DIR}/boot/
cp -r "${BUILD_DIR}/${ARCH}/${CARGO_DIR}/libmenix.so" ${INSTALL_DIR}/boot/menix
"""
