[package]
name = "kernel"
version = "latest"
archs = ["x86_64"]

[dependencies]
build = ["tools-host"]

[[sources]]
repo = "https://github.com/menix-os/menix"
path = "../../../menix"

[configure]
script = """
if [ $DEBUG == "1" ]; then {
	cmake -B $BUILD_DIR -S $SOURCE_DIR -DCMAKE_BUILD_TYPE=Debug
} else {
	cmake -B $BUILD_DIR -S $SOURCE_DIR -DCMAKE_BUILD_TYPE=Release
} fi

"""

[build]
script = """
cmake --build $BUILD_DIR -j$THREADS
"""

[install]
script = """
mkdir -p $INSTALL_DIR/boot/
cp -r $BUILD_DIR/bin/menix $INSTALL_DIR/boot/
"""
