[package]
name = "kernel"
version = "latest"
archs = ["x86_64"]

[dependencies]
build = ["tools-host"]

[[sources]]
repo = "https://github.com/menix-os/menix"
branch = "main"
path = "../../../menix"

[configure]
script = """
if [ ${DEBUG} == "1" ]; then {
	export CMAKE_BUILD_TYPE=Debug
} else {
	export CMAKE_BUILD_TYPE=Release
} fi

cmake -B ${BUILD_DIR} -S ${SOURCE_DIR} -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
"""

[build]
script = """
cmake --build ${BUILD_DIR} -j${THREADS}
"""

[install]
script = """
mkdir -p ${INSTALL_DIR}/boot/
cp -r ${BUILD_DIR}/bin/menix ${INSTALL_DIR}/boot/
"""
