[package]
name = "kernel"
version = "latest"
archs = ["x86_64"]

[dependencies]
build = ["tools-host"]

[[sources]]
repo = "https://github.com/menix-os/menix"
branch = "main"
path = "../../../menix"

[build]
script = """
if [ "${DEBUG}" == "0" ]; then
	export BUILD_MODE="--release"
fi

cargo \
	+nightly \
	rustc \
	--bin menix \
	${BUILD_MODE} \
	--manifest-path "${SOURCE_DIR}/kernel/Cargo.toml" \
	--target "${SOURCE_DIR}/toolchain/${ARCH}.json" \
	--config "${SOURCE_DIR}/.cargo/config.toml" \
	--target-dir "${BUILD_DIR}" \
"""

[install]
script = """
if [ "$DEBUG" == "0" ]; then
	export CARGO_DIR="release"
else
	export CARGO_DIR="debug"
fi

mkdir -p ${INSTALL_DIR}/boot/
cp -r "${BUILD_DIR}/${ARCH}/${CARGO_DIR}/menix" ${INSTALL_DIR}/boot/
"""
