[package]
name = "host-gcc"
version = "latest"
archs = ["x86_64"]
host = true

[[sources]]
repo = "https://gcc.gnu.org/git/gcc.git"
branch = "master"
patches = ["menix.patch"]

[dependencies]
host = ["make", "automake", "gcc", "ld", "as", "pkg-config"]
build = ["host-binutils", "mlibc-headers"]

[configure]
script = """
    CXXFLAGS_FOR_TARGET="${TARGET_CFLAGS}" \
    CFLAGS_FOR_TARGET="${TARGET_CFLAGS}" \
${SOURCE_DIR}/configure \
	--target=${OS_TRIPLET} \
	--disable-shared \
	--enable-languages=c,c++,lto \
	--with-sysroot="${INSTALL_DIR}" \
	--prefix="${PREFIX}" \
	--disable-multilib \
	--without-headers \
	--without-newlib \
	--disable-hosted-libstdcxx \
	--disable-wchar_t
"""

[build]
script = """
make -j${THREADS} all-gcc
"""

[install]
script = """
DESTDIR="${INSTALL_DIR}" make install-gcc
"""
