[package]
name = "host-gcc"
version = "latest"
archs = ["x86_64"]
host = true

[[sources]]
repo = "https://gcc.gnu.org/git/gcc.git"
branch = "master"
patches = ["menix.patch"]

[dependencies]
host = ["make", "automake", "gcc", "ld", "as", "pkg-config"]
build = ["host-binutils", "mlibc-headers"]

[configure]
script = """
${SOURCE_DIR}/configure \
	--target=${OS_TRIPLET} \
	--enable-languages=c,c++,lto \
	--with-sysroot="${SYSROOT_DIR}" \
	--prefix="${PREFIX}" \
	--enable-threads=posix \
	--disable-multilib \
	--enable-shared \
	--enable-host-shared \
	--with-pic
"""

[build]
script = """
make -j${THREADS} all-gcc all-target-libgcc
"""

[install]
script = """
DESTDIR="${INSTALL_DIR}" make install-gcc install-target-libgcc
"""
