[package]
name = "binutils-host"
version = "latest"
archs = ["x86_64"]

[[sources]]
repo = "https://sourceware.org/git/binutils-gdb.git"
branch = "master"

[dependencies]
host = ["make"]


[build]
patches = ["menix.patch"]
script = """

"""

[install]
script = """

"""
