[package]
name = "binutils-host"
version = "latest"
archs = ["x86_64"]

[[sources]]
repo = "https://sourceware.org/git/binutils-gdb.git"
branch = "master"

[[patches]]
file = "menix.patch"

[[deps.build]]
name = "make"

[build]
script = """

"""

[install]
script = """

"""
