[package]
name = "host-automake"
version = "1.16.5"
archs = ["x86_64"]
host = true

[[sources]]
url = "https://ftp.gnu.org/gnu/automake/automake-1.16.5.tar.gz"
path = "automake-1.16.5.tar.gz"
patches = ["menix.patch"]

[dependencies]
host = ["autoconf"]
build = ["host-autoconf"]

[configure]
script = """
${SOURCE_DIR}/configure --host="${OS_TRIPLET}" --prefix="${HOST_DIR}/${PREFIX_HOST}"
"""

[build]
script = """
make -j${THREADS}
"""

[install]
script = """
make install
"""
