[package]
name = "host-libgcc-binaries"
version = "latest"
archs = ["x86_64"]
host = true

[[sources]]
repo = "https://github.com/osdev0/libgcc-binaries"
branch = "trunk"

[install]
script = """
mkdir -p ${INSTALL_DIR}${LIB_DIR}
cp ${SOURCE_DIR}/libgcc-${ARCH}.a ${INSTALL_DIR}${LIB_DIR}/libgcc.a
"""
