[package]
name = "builder"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
clap = { version = "4.5.20", features = ["derive"] }
decompress = "0.6.0"
serde = { version = "1.0.215", features = ["derive"] }
toml = "0.8.19"
