[package]
name = "gcc-host"
version = "latest"
archs = ["x86_64"]

[[sources]]
repo = "https://gcc.gnu.org/git/gcc.git"
branch = "master"

[[patches]]
file = "menix.patch"

[[deps.build]]
name = "make"

[[deps.runtime]]

[build]
script = """

"""

[install]
script = """

"""
