[package]
name = "gcc-host"
version = "latest"
revision = 1
architectures = ["x86_64"]

[[sources]]
git = "https://gcc.gnu.org/git/gcc.git"
branch = "master"

[[patches]]
file = "menix.patch"

[[deps.build]]
name = "make"

[[deps.runtime]]

[build]
script = ""

[install]
