[package]
name = "gcc-host"
version = "latest"
archs = ["x86_64"]

[[sources]]
repo = "https://gcc.gnu.org/git/gcc.git"
branch = "master"

[dependencies]
host = ["make"]

[build]
patches = ["menix.patch"]
script = """

"""

[install]
script = """

"""
