[package]
name = "libgcc-binaries"
version = "latest"
archs = ["x86_64"]

[[sources]]
repo = "https://github.com/osdev0/libgcc-binaries"
branch = "trunk"

[install]
script = """
mkdir -p ${INSTALL_DIR}/usr/lib/
cp ${SOURCE_DIR}/libgcc-${ARCH}.a ${INSTALL_DIR}/usr/lib/libgcc.a
"""
