[package]
name = "init"
version = "latest"
archs = ["x86_64"]

[dependencies]
host = ["cmake", "gcc", "as", "ld"]
build = ["host-gcc", "host-binutils"]
runtime = ["initrd"]

[[sources]]
repo = "https://github.com/menix-os/init"
branch = "main"
path = "../../../init"

[configure]
script = """
"""

[build]
script = """
${OS_TRIPLET}-gcc ${SOURCE_DIR}/main.c -o init -ffreestanding -nostdlib
"""

[install]
script = """
mkdir -p ${INSTALL_DIR}/usr/sbin/
cp -r ${BUILD_DIR}/init ${INSTALL_DIR}/usr/sbin/init
"""
